[build]
  publish = "public"
  command = "hugo --baseURL=https://www.taylorsavage.com/"

[context.production.environment]
  HUGO_VERSION = "0.40.3"
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://www.taylorsavage.com"